Update for new starter kits
statamic/cli pull request #31
Opened 2021-05-21 03:05 UTC by jesseleite

2021-07-19 21:42 UTC, jasonvarga commented on src/NewCommand.php
> +            return $this;
I think this is different now. When I try to `statamic new mysite non-existent/kit` the JSON would be `{"data": false}`. I don't think `$details` is ever `false` anymore.

2021-07-19 23:07 UTC, jasonvarga requested changes

2021-07-19 23:07 UTC, jasonvarga commented on src/NewCommand.php
> +        $question->setHidden(true);
I don't think this needs to be hidden. Kinda threw me off when I pasted in my key.

2021-07-23 18:11 UTC, jesseleite commented on src/NewCommand.php
> +            return $this;
Good catch, thanks

2021-08-16 23:03 UTC, jasonvarga commented
Instead of a yaml file with the starter kits, can't we pull them from the marketplace?

2021-08-17 00:42 UTC, jackmcdade commented
@jasonvarga Yes please. In fact, we should probably just point them to the Marketplace instead of trying to populate the list of them here. For now it's just a few, but in a few weeks/months there could be dozens. It'll be easier to cut it off now rather than later.

2021-08-17 13:10 UTC, jasonvarga commented
So you want to remove this screen? Just make it a regular text input?

![image](https://user-images.githubusercontent.com/105211/129731373-553e6ef4-4014-4870-9e18-78d82d85fa37.png)

2021-08-17 13:12 UTC, jackmcdade commented
Maybe? What options do we have that don't involve simply listing all possible kits?

2021-08-17 13:25 UTC, jasonvarga commented
Some kind of search maybe... But that seems silly on the cli.

We could do autocompletion though.

2021-08-17 13:28 UTC, jackmcdade commented
Maybe we do a prompt – like...

```
What do you want to do?
[0] Start with the default empty site
[1] Use a Starter Kit
```

And then if they pick `[1]`...

```
Enter the name of the Starter Kit (find them at statamic.com/stater-kits):
> autocomplete field
```

2021-08-17 13:29 UTC, jasonvarga commented
We can do that.

2021-08-17 13:44 UTC, jackmcdade commented
![8ukb](https://user-images.githubusercontent.com/44739/129736754-df04710c-9369-42c2-9a12-fcd275600d07.gif)

2021-08-24 15:06 UTC, jesseleite commented
There we go! We can do the autocomplete later though.

![image](https://user-images.githubusercontent.com/5187394/130641318-a8d0542f-b869-4870-9ff3-ddf770593470.png)

2021-08-24 15:31 UTC, jasonvarga approved these changes

2021-08-24 15:37 UTC, jasonvarga approved these changes

2021-08-24 15:38 UTC, merged